development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sport_app_dev
  pool: 5
  username: alexandr
  password: qwerty22

test:
  adapter: postgresql
  encoding: unicode
  database: sport_app_test
  pool: 5
  username: alexandr
  password: qwerty22

production:
  adapter:  postgresql
  encoding: unicode
  host:     localhost 
  database: <%= ENV['SPORT_APP_DB'] %>
  pool: 5
  username: <%= ENV['SPORT_APP_DB_USER'] %>
  password: <%= ENV['SPORT_APP_DB_PASSWORD'] %>
